#jwlam; Lam, Justin

CC=g++
CFLAGS=-Wall -ansi 

TARGET=mysudsolve
HEADERS=puzzle.h cell.h
SOURCES=main.cpp puzzle.cpp cell.cpp

all:    $(SOURCES) $(HEADERS)
	$(CC) $(CFLAGS) -o $(TARGET) $(SOURCES)

clean:
	rm -f $(TARGET)

